
CREATE TABLE LEVELS(
    id BIGSERIAL PRIMARY KEY,
    min_level INT NOT NULL,
    max_level INT NOT NULL
);

CREATE TABLE GAME
(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    priority DECIMAL(17, 1) NOT NULL,
    level_id INT NOT NULL
);
ALTER TABLE GAME ADD FOREIGN KEY (level_id) REFERENCES LEVELS(id);

CREATE TABLE COUNTRY
(
    id BIGSERIAL PRIMARY KEY,
    country VARCHAR(50) NOT NULL,
    code VARCHAR(3) NOT NULL
);

CREATE TABLE GAME_COUNTRY
(
    id BIGSERIAL PRIMARY KEY,
    game_id INT NOT NULL,
    country_id INT NOT NULL
);
ALTER TABLE GAME_COUNTRY ADD FOREIGN KEY (game_id) REFERENCES GAME(id);
ALTER TABLE GAME_COUNTRY ADD FOREIGN KEY (country_id) REFERENCES COUNTRY(id);

CREATE TABLE items
(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE GAME_ITEMS
(
    id BIGSERIAL PRIMARY KEY,
    game_id INT NOT NULL,
    item_id INT NOT NULL
);
ALTER TABLE GAME_ITEMS ADD FOREIGN KEY (game_id) REFERENCES GAME(id);
ALTER TABLE GAME_ITEMS ADD FOREIGN KEY (item_id) REFERENCES ITEMS(id);

CREATE TABLE CAMPAIGN
(
    id BIGSERIAL PRIMARY KEY,
    campaign_name VARCHAR(50) NOT NULL,
    game_id INT NOT NULL,
    start_date DATETIME NOT NULL,
    end_date DATETIME NOT NULL,
    enabled BIT NOT NULL,
    last_updated DATETIME NOT NULL
);
ALTER TABLE CAMPAIGN ADD FOREIGN KEY (game_id) REFERENCES GAME(id);

CREATE TABLE INVENTORY
(
    id BIGSERIAL PRIMARY KEY,
    cash DECIMAL(17, 1) NOT NULL,
    coins INT NOT NULL
);

CREATE TABLE INVENTORY_ITEMS
(
    id BIGSERIAL PRIMARY KEY,
    inventory_id INT NOT NULL,
    item_id INT NOT NULL
);
ALTER TABLE INVENTORY_ITEMS ADD FOREIGN KEY (inventory_id) REFERENCES INVENTORY(id);
ALTER TABLE INVENTORY_ITEMS ADD FOREIGN KEY (item_id) REFERENCES ITEMS(id);

CREATE TABLE CLAN
(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE PLAYER_PROFILE
(
    id BIGSERIAL PRIMARY KEY,
    player_id VARCHAR(50) NOT NULL,
    credential VARCHAR(50) NOT NULL,
    created DATETIME NOT NULL,
    modified DATETIME NOT NULL,
    last_session DATETIME NOT NULL,
    total_spent DECIMAL(17, 1) NOT NULL,
    total_refund DECIMAL(17, 1) NOT NULL,
    total_transactions INT NOT NULL,
    last_purchase DATETIME NOT NULL,
    player_level INT NOT NULL,
    xp INT NOT NULL,
    total_playtime INT NOT NULL,
    country VARCHAR(50) NOT NULL,
    language VARCHAR(50) NOT NULL,
    birthdate DATETIME NOT NULL,
    gender VARCHAR(50) NOT NULL,
    inventory_id INT NOT NULL,
    clan_id INT NOT NULL
);
ALTER TABLE PLAYER_PROFILE ADD FOREIGN KEY (inventory_id) REFERENCES INVENTORY(id);
ALTER TABLE PLAYER_PROFILE ADD FOREIGN KEY (clan_id) REFERENCES CLAN(id);

CREATE TABLE DEVICES
(
    id BIGSERIAL PRIMARY KEY,
    model VARCHAR(50) NOT NULL,
    carrier VARCHAR(50) NOT NULL,
    firmware INT NOT NULL,
    player_profile_id INT NOT NULL
);
ALTER TABLE DEVICES ADD FOREIGN KEY (player_profile_id) REFERENCES PLAYER_PROFILE(id);

CREATE TABLE PLAYER_PROFILE_CAMPAIGN
(
    id BIGSERIAL PRIMARY KEY,
    player_profile_id INT NOT NULL,
    campaign_id INT NOT NULL
);
ALTER TABLE PLAYER_PROFILE_CAMPAIGN ADD FOREIGN KEY (player_profile_id) REFERENCES PLAYER_PROFILE(id);
ALTER TABLE PLAYER_PROFILE_CAMPAIGN ADD FOREIGN KEY (campaign_id) REFERENCES CAMPAIGN(id);
